# Environment variables:
#
# See `strategy/anitya/.env.template`.

services:
  anitya:
    # https://github.com/fedora-infra/anitya/blob/master/container-compose.yml
    #
    # `postgres` Docker image docs:
    #   - <https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/>
    #   - <https://github.com/docker-library/docs/blob/master/postgres/README.md>
    image: postgres:15.6
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ${ANITYA_DOCKER_POSTGRES_DATA_DIR:-./work/postgres/data}:/var/lib/postgresql/data
      - ${ANITYA_DUMP_FILE:?Need to define dump file}:/dump/anitya.dump.xz
      - ${THIS_DIR_ABSPATH:?Need to set THIS_DIR_ABSPATH}/bin/db-dump-restore:/script/db-dump-restore
      ## set shared memory limit when deploy via swarm stack
      #- type: tmpfs
      #  target: /dev/shm
      #  tmpfs:
      #    size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${ANITYA_PGPASSWORD:-password}
      ANITYA_PGDATABASE: ${ANITYA_PGDATABASE:-anitya}
    ports:
      - "${ANITYA_PGPORT:-5432}:5432"
